### ISSUE TITLE
TypeError: Cannot read property 'string' of undefined

### ISSUE THREAD

**Issue by gundamftw** [potapovDim/react-eyedropper#2]
I keep getting this error "TypeError: Cannot read property 'string' of undefined". 

I tested with a brand new React app, copied everything from the sample code to App.js except the image div, and it still reports the problem. This is the area that it highlights.

`
EyeDropper.propTypes = {
  title: _react.PropTypes.string,
  className: _react.PropTypes.string,
  initializedColor: _react.PropTypes.func.isRequired,
  onInit: _react.PropTypes.func
};
`

**Comment by danger9224** [comment]
I also have the same issue.

**Comment by potapovDim** [comment]
@gundamftw and @dandesz198 This issue is filed by, @gundamftw
